KTH/kurs-pm-data-admin-web

i18n/messages.en.js, i18n/messages.se.js, public/css/node-web.scss, public/js/app/components/ProgressTitle.jsx, public/js/app/pages/ChoiceOptions.jsx, public/js/app/pages/MemoContainer.jsx, public/js/app/pages/MemoEdition.jsx
- New design and elements location for step 2
- Saving fresh kopps data to db
- Refactor onSave function
- Added minor styles
=> Step 2 edit mode

i18n/messages.en.js, public/js/app/pages/ChoiceOptions.jsx, public/js/app/util/helpers.js
- memo name  for api based on common language (if at least one is English, then memo will be in English as well as its name)
- string for languageOfInstructions combined of languages of chosen rounds, translated to common language
- round name based on user interface language
=> Language changes

i18n/messages.en.js, i18n/messages.se.js
KIP-434 Sidomeny med lösning för länkar
=> Correction to side menu label in preview

i18n/messages.en.js, i18n/messages.se.js, public/js/app/components/ControlPanel.jsx, public/js/app/pages/ChangePublished.jsx, public/js/app/pages/ChoiceOptions.jsx, public/js/app/pages/MemoContainer.jsx, public/js/app/util/constants.js
- add Avsluta - Finish and Save functions
- Redirect after finish to start admin page 
- prepared button text and function for Avbryt - Finish and Remove for next feature
=> Add cancel function for Create New And Publish flow

public/css/node-web.scss, public/js/app/components/preview/CourseHeader.jsx
KIP-522 Kursens kod och namn ska vara H4
och ev klassen secondTitle el. motsvarande
=> More style corrections to course header in preview

config/serverSettings.js, i18n/messages.en.js, i18n/messages.se.js, server/controllers/changePublishedCtrl.js, server/controllers/choiceOptionsCtrl.js, server/controllers/memoCtrl.js, server/controllers/previewCtrl.js, server/server.js, server/views/partials/kthHeader.handlebars
- cortina block
- language
- KTH logo
- link to Administrera Om kursen [courseCode]
=> Fix head menu

i18n/messages.en.js, i18n/messages.se.js, package.json, public/css/node-web.scss, public/js/app/components/ControlPanel.jsx, public/js/app/components/NewSectionEditor.jsx, public/js/app/components/StandardEditorPerTitle.jsx, public/js/app/pages/ChangePublished.jsx, public/js/app/pages/ChoiceOptions.jsx, public/js/app/pages/MemoContainer.jsx, public/js/app/stores/RouterStore.js, server/controllers/changePublishedCtrl.js, server/controllers/choiceOptionsCtrl.js, server/controllers/memoCtrl.js, server/controllers/previewCtrl.js, server/koppsApi.js, server/views/partials/kthHeader.handlebars
- Removed autosave plugins for editor and removedraft
- Added font family for preview and memo page
- Fixed heading with translation link
- Fixed bug with Shedule link
=> Check literature and fixes

i18n/messages.se.js, public/js/app/components/Collapse.jsx, public/js/app/components/ContentHead.jsx, public/js/app/components/ControlPanel.jsx, public/js/app/components/NewSectionEditor.jsx, public/js/app/components/PageHead.jsx, public/js/app/components/Section.jsx, public/js/app/components/SectionForNonEditable.jsx, public/js/app/components/StandardEditorPerTitle.jsx, public/js/app/components/VisibilityInfo.jsx, public/js/app/pages/MemoContainer.jsx, public/js/app/pages/PreviewContainer.jsx, public/js/app/stores/RouterStore.js, public/js/app/util/fieldsByType.js, server/controllers/memoCtrl.js, server/defaultValues.js, test/mocks/RouterStore.js, test/mocks/RouterStoreWithChosenMemo.js, test/mocks/memoData/generateExtraHeaders.js, test/mocks/memoData/generateStandardMemoData.js, test/mocks/memoData/generateStandardVisibility.js, test/mocks/memoData/memoTypes.js, test/mocks/memoData/standardContentId.js, test/mocks/miniMemos.js, test/unit/CreateNewMemo.test.js, test/unit/MemoContainerNewDraft.test.js, test/unit/MemoContainerPublished.test.js, test/unit/memoCtrl.test.js
- Refactor Memo Container
- Tests for page memo container 'Create new and publish' 
- Tests for page memo container 'Edit published'
- Created data structure for further tests
=> Tests for second step

public/css/node-web.scss, public/js/app/components/SectionMenu.jsx
Anna's feedback: eye icon needs to be 20 px.
**----------Before------------**
**-----------Only height and width of Icon adjusted----------**
**------------After---------**
=> fix: size of eye icon

public/js/app/components/ActionModalCourseRounds.jsx
https://jira.sys.kth.se/browse/KUI-1023
This fixes
* saving of additional kurstillfälle
* repeated saving of additional kurstillfälle to a draft
=> fix(KUI-1023)

i18n/messages.en.js, i18n/messages.se.js, public/js/app/hooks/useToast.js, public/js/app/pages/PreviewContainer.jsx, server/controllers/previewCtrl.js, server/kursPmDataApi.js, server/utils/errorUtils.js, test/unit/ChangePublished.test.js
* surface 4xx errors
* added useToast hook
=> feat(KUI-1036): handle 4xx errors from kurs-pm-data-api

public/js/app/components/details/CollapseMemoIntroduction.jsx
=> fix(KUI-1085): update text

i18n/messages.se.js, public/css/node-web.scss, test/unit/ChangePublished.test.js
https://jira.sys.kth.se/browse/KUI-1153
=> Kui1153 style changes

i18n/messages.en.js
Added changes for english translation
=> KUI1153 Fix: english translation list

i18n/messages.en.js, i18n/messages.se.js
Correct missing or wrong texts.
=> KUI-1139: correct texts

i18n/messages.en.js, i18n/messages.se.js
This PR changes that the Ethical Policy opens in a new tab.
=> fix(KUI-1139): link target

server/kursInfoApi.js, test/mock-api/config.js, test/mock-api/responses.js
switch to new courseInfo endpoint instead of deprecated sellingText endpoint
=> feat(KUI-1289): use new courseInfo endpoint

package-lock.json, public/js/app/components/SectionForNonEditable.jsx, public/js/app/components/preview/CourseContacts.jsx, public/js/app/util/disableLinksInHtml.js
- Added utility function which deactivates the profile page links for now
=> Deactivated profile page links

package-lock.json, package.json, test/unit/test-MemoCtrl.js
- Removed `mockery` (critical)
----------------------------------------------------------------------
- Updated `tinymce` to `7.4.1`
- Updated `@tinymce/tinymce-react` to `5.1.1` 
Impact: 
- Stricter HTML/SVG Sanitization: Content that was previously allowed, especially in SVGs or custom HTML, may now be stripped out to prevent XSS vulnerabilities.
- XML Content Handling Changes: Differences in parsing XML-related content (like CDATA or Processing Instructions) may alter how certain data is processed or displayed.
- Default Configuration Adjustments: Security-related updates might modify default behavior, impacting plugins or features relying on older configurations.
- Plugin Compatibility: Custom or third-party plugins that interact with content sanitization could require updates to …
=> KUI-1537: dependency updates

server/controllers/memoCtrl.js, server/koppsApi.js
Problem described in [this ticket](https://kth-se.atlassian.net/browse/KUI-1702)
Added some error handling in memoCtrl.js and cleaned up comments.
=> KUI-1702 examination modules undefined bug fix

package-lock.json, package.json, server/controllers/memoCtrl.js, server/ladokApi.js
Related to this [PR](https://github.com/KTH/studadm-om-kursen-packages/pull/29)
=> KUI-1728: refactored formatting function
